title: Ilirjana Hyseni
logo: items/Lily-circle1.png
description: I am a Data Scientist with a strong foundation in scientific research and data analysis, honed through years education and hands-on experience in various research roles. Proven track record as an author and co-author of numerous peer-reviewed papers in top scientific journals, including Nature Communications. I am currently completing a Data Science and Business Analytics postgraduate program with a focus on Machine Learning.
show_downloads: true 
theme: jekyll-theme-minimal
