title: Ilirjana Hyseni
logo: items/Lily-circle1.png
description: Experienced Data Scientist with a strong foundation in scientific research and data analysis, honed through years of STEM education and hands-on experience in various research roles. I am currently completing a Data Science and Business Analytics postgraduate program with a focus on Machine Learning. 
show_downloads: true 
theme: jekyll-theme-minimal
